name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:             
          - name: Windows 64
            os: windows-latest
            build-mode: WIN64
            binary: libtpaex64.dll

          - name: Windows 32
            os: windows-latest
            build-mode: WIN32
            binary: libtpaex32.dll

          - name: Linux 64
            os: ubuntu-latest
            build-mode: LINUX64
            binary: libtpaex64.so

          - name: Linux AArch64  
            os: ubuntu-latest
            build-mode: LINUX-AARCH64
            binary: libtpaex64.so.aarch64

          - name: MacOS 64
            os: macos-latest
            build-mode: MACOS
            binary: libtpaex64.dylib

          - name: MacOS AArch64
            os: macos-latest
            build-mode: MACOS-AARCH64
            binary: libtpaex64.dylib.aarch64

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: Install FPC and Lazarus on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install fpc --version=3.2.2
          choco install lazarus --version=2.2.4

      - name: Install FPC and Lazarus on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          if [ "${{ matrix.config.build-mode }}" == "LINUX-AARCH64" ]; then
            sudo dpkg --add-architecture arm64
            sudo apt-get update
            sudo apt-get install -y fpc-3.2.2-cross-aarch64
          else
            sudo apt-get install -y fpc-3.2.2
          fi
          sudo apt-get install -y lazarus-2.2.4

      - name: Install FPC and Lazarus on macOS
        if: runner.os == 'macOS'
        run: |
          brew install fpc lazarus
          if [ "${{ matrix.config.build-mode }}" == "MACOS-AARCH64" ]; then
            # Set up the FPC cross-compiler for AArch64 using fpcupdeluxe
            curl -O "https://github.com/LongDirtyAnim/fpcupdeluxe/releases/download/latest/fpcupdeluxe_macOS_x86_64"
            chmod +x fpcupdeluxe_macOS_x86_64
            ./fpcupdeluxe_macOS_x86_64 --nobuilddir --nodownloadfpcsrc --nobuildlazarussrc --fpcver=3.2.2 --lazver=2.2.4 --crosscompiler-aarch64
          fi

      - name: Build Library tpaex
        run: |
          lazbuild --build-mode=${{ matrix.config.build-mode }} tpaex.lpi

      - name: Upload Binary 
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.binary }}
          path: ${{ matrix.config.binary }}
