name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runs-on }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Win64
            runs-on: windows-latest
            build-mode: WIN64
            binary: libtpaex64.dll
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-win64.exe
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

          - name: Win32
            runs-on: windows-latest
            build-mode: WIN32
            binary: libtpaex32.dll
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-win64.exe
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

          - name: Linux64
            runs-on: ubuntu-22.04
            build-mode: LINUX64
            binary: libtpaex64.so
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-linux
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

          - name: Linux Arm64
            runs-on: ubuntu-22.04-arm
            build-mode: LINUX-AARCH64
            binary: libtpaex64.so.aarch64
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-linux
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

          - name: Mac Arm64
            runs-on: macos-26
            build-mode: MACOS-AARCH64
            binary: libtpaex64.dylib.aarch64
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-aarch64-darwin
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

          - name: Mac Intel
            runs-on: macos-15-intel
            build-mode: MACOS
            binary: libtpaex64.dylib
            fpclazup-url: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.4.0g/fpclazup-x86_64-darwin
            fpclazup-lazcommit: 98f9c7a7a102139e43b39050ebbb5c48d805f59f # 4.4
            fpclazup-fpccommit: d3a5f442eeff766a60cd7177536a9db7cc54875c # 3.2.4

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Install Custom Lazarus
        uses: ollydev/setup-lazarus@v4
        with:
          fpclazup-url: ${{ matrix.config.fpclazup-url }}
          fpclazup-lazcommit: ${{ matrix.config.fpclazup-lazcommit }}
          fpclazup-fpccommit: ${{ matrix.config.fpclazup-fpccommit }}

      - name: Build Library tpaex
        run: |
          lazbuild --build-mode=${{ matrix.config.build-mode }} tpaex.lpi

      - name: Upload Simba Binary
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ${{ matrix.config.binary }}
          path: ${{ matrix.config.binary }}
